name: gotest

on:
  push:
    branches: ["main"]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - name: lint
        uses: golangci/golangci-lint-action@v6
      - name: test
        run: go test ./... -cover
